import {
  Utensils,
  ShoppingBag,
  Car,
  Home,
  Receipt,
  HeartPulse,
  GraduationCap,
  Clapperboard,
  Plane,
  Smartphone,
  MoreHorizontal,
  Briefcase,
  Laptop,
  TrendingUp,
  Gift,
  Wallet,
  Landmark,
  // Extended set
  Coffee,
  Pizza,
  ShoppingCart,
  Bus,
  TrainFront,
  Fuel,
  Bike,
  Hotel,
  Bed,
  Shirt,
  Dumbbell,
  Trophy,
  Medal,
  Music,
  Headphones,
  Gamepad2,
  Tv,
  Camera,
  Ticket,
  PartyPopper,
  Wine,
  Beer,
  Cake,
  Apple,
  Carrot,
  Fish,
  Beef,
  Dog,
  Cat,
  PawPrint,
  Baby,
  Stethoscope,
  Pill,
  Wifi,
  Phone,
  Zap,
  Droplet,
  Flame,
  Lightbulb,
  Sofa,
  Wrench,
  Scissors,
  Palette,
  BookOpen,
  Church,
  School,
  Building2,
  CreditCard,
  Banknote,
  Coins,
  HandCoins,
  PiggyBank,
  Bitcoin,
  Umbrella,
  Sun,
  Trees,
  Flower,
  Cigarette,
  ArrowLeftRight,
  Users,
  type LucideIcon,
} from 'lucide-react'

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  'shopping-bag': ShoppingBag,
  car: Car,
  home: Home,
  receipt: Receipt,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  clapperboard: Clapperboard,
  plane: Plane,
  smartphone: Smartphone,
  'more-horizontal': MoreHorizontal,
  briefcase: Briefcase,
  laptop: Laptop,
  'trending-up': TrendingUp,
  gift: Gift,
  // Food & drink
  coffee: Coffee,
  pizza: Pizza,
  wine: Wine,
  beer: Beer,
  cake: Cake,
  apple: Apple,
  carrot: Carrot,
  fish: Fish,
  beef: Beef,
  // Shopping & bills
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  banknote: Banknote,
  coins: Coins,
  'hand-coins': HandCoins,
  'piggy-bank': PiggyBank,
  bitcoin: Bitcoin,
  // Transport & travel
  bus: Bus,
  train: TrainFront,
  fuel: Fuel,
  bike: Bike,
  hotel: Hotel,
  bed: Bed,
  umbrella: Umbrella,
  // Lifestyle & leisure
  shirt: Shirt,
  dumbbell: Dumbbell,
  trophy: Trophy,
  medal: Medal,
  music: Music,
  headphones: Headphones,
  gamepad: Gamepad2,
  tv: Tv,
  camera: Camera,
  ticket: Ticket,
  'party-popper': PartyPopper,
  palette: Palette,
  book: BookOpen,
  // Health & family
  stethoscope: Stethoscope,
  pill: Pill,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  'paw-print': PawPrint,
  // Home & utilities
  wifi: Wifi,
  phone: Phone,
  zap: Zap,
  droplet: Droplet,
  flame: Flame,
  lightbulb: Lightbulb,
  sofa: Sofa,
  wrench: Wrench,
  scissors: Scissors,
  cigarette: Cigarette,
  // Places & nature
  church: Church,
  school: School,
  building: Building2,
  sun: Sun,
  trees: Trees,
  flower: Flower,
  'arrow-left-right': ArrowLeftRight,
  users: Users,
}

export const ACCOUNT_ICONS: Record<string, LucideIcon> = {
  cash: Wallet,
  bank: Landmark,
  'mobile-wallet': Smartphone,
}

export function getCategoryIcon(key: string): LucideIcon {
  return CATEGORY_ICONS[key] ?? MoreHorizontal
}

export function getAccountIcon(key: string): LucideIcon {
  return ACCOUNT_ICONS[key] ?? Wallet
}
